### ISSUE TITLE
MaxBuffer exceeded for fossology/nomos

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#163]
We bumped up the limit here: https://github.com/clearlydefined/crawler/pull/135/files

Still seeing some instances of this in the past week of crawling

Curious how close we are to the limit we set when these run these or if there are any other alternatives to workaround

```
Error: stdout maxBuffer exceeded
    at Socket.onChildStdout (child_process.js:328:14)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:597:20)
    
  cmd: 'cd /opt/fossology/src/nomos/agent && ./nomossa -ld /tmp/cd-glQQL7/TypeScript'
```

Here is the list of affected components

 - git/github/apple/turicreate/4bd7f4634b75c0d825f8503c06b12103660c092c	
 - git/github/apple/turicreate/816466293fade4f29df8acccdda08c3d43dfef17	
 - git/github/apple/turicreate/e4aad253af795b8364fc6602e4772a1ee1dcf0f7	
 - git/github/aws/aws-sdk-net/649e886d9f7a4705632dfbd4fa485350166f53b5	
 - git/github/directproject/nhin-d/bb8588a00e17e954aeeaa5119b706ac904c9d10f
 - git/github/maidsafe-archive/maidsafe/01cc5cca514239e43d06b536f396cbe2e1f2a5bf	
 - git/github/stichting-minix-research-foundation/minix/588a35b9293dcbc89a45881940d00c2ae6d13801	
 - git/github/trailofbits/mcsema/c2fd1e99b0d8862e36fc011c67f078cfe3a6ccd1	
 - npm/npmjs/-/typescript/2.8.1	
 - npm/npmjs/-/typescript/2.8.3	
 - npm/npmjs/-/typescript/2.8.4	
 - npm/npmjs/-/typescript/2.9.1	
 - npm/npmjs/-/typescript/3.0.1

**Comment by dabutvin** [comment]
can we pipe this to a file instead of stdout?
