### ISSUE TITLE
[Scancode] Some files failed to scan properly

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#179]
Getting errors from scancode aout scanning files improperly

Here are 2 examples:

 - https://github.com/sequelize/sequelize/blob/master/package.json
 - https://github.com/Urthen/case-sensitive-paths-webpack-plugin/blob/master/demo/package.json

Full trace output:

```
{ Error: Command failed: cd /opt/scancode-toolkit-2.9.2 && ./scancode --copyright --license --info --package --license-diag --only-findings  --strip-root --timeout 1000 -n 2 --json-pp /tmp/cd-MUvva5 /tmp/cd-m7zFHh/sequelize
Setup plugins...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages with 2 process(es)...
Scanning done.
Some files failed to scan properly:
Path: package.json
Summary:        info, copyrights, licenses, packages with 2 process(es)
Errors count:   0
Scan Speed:     3.65 files/sec. 39.01 KB/sec.
Initial counts: 362 resource(s): 311 file(s) and 51 directorie(s) 
Final counts:   4 resource(s): 4 file(s) and 0 directorie(s) for 214.13 KB
Timings:
  setup_scan:licenses: 4.69s
  setup: 4.69s
  inventory: 0.39s
  scan: 85.25s
  post-scan:package-root: 0.74s
  post-scan: 0.74s
  total: 91.13s

    at AppInsightsAsyncCorrelatedErrorWrapper.ZoneAwareError (/opt/service/node_modules/zone.js/dist/zone-node.js:811:33)
    at new AppInsightsAsyncCorrelatedErrorWrapper (/opt/service/node_modules/applicationinsights/out/AutoCollection/CorrelationContextManager.js:182:18)
    at ChildProcess.exithandler (child_process.js:276:12)
    at ZoneDelegate.invokeTask (/opt/service/node_modules/zone.js/dist/zone-node.js:275:35)
    at Zone.runTask (/opt/service/node_modules/zone.js/dist/zone-node.js:151:47)
    at ChildProcess.ZoneTask.invoke (/opt/service/node_modules/zone.js/dist/zone-node.js:345:33)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cd /opt/scancode-toolkit-2.9.2 && ./scancode --copyright --license --info --package --license-diag --only-findings  --strip-root --timeout 1000 -n 2 --json-pp /tmp/cd-MUvva5 /tmp/cd-m7zFHh/sequelize' }
```

**Comment by dabutvin** [comment]
@pombredanne fyi

**Comment by pombredanne** [comment]
@dabutvin Thank you for the report: These bugs have been fixed in ScanCode in the develop branch with this commit https://github.com/nexB/scancode-toolkit/commit/a6152cfc59e62bc0bae6e716f675f92a175414c8 so I guess the thing would be to decide when to update

**Comment by pombredanne** [comment]
Note also that the fact that a single file failed to scan does not invalidate the scan at large.

**Comment by pombredanne** [comment]
For reference the failure stack trace when running in verbose mode is :
```
$ scancode --copyright --license --info --package --license-diag --only-findings  --strip-root --timeout 1000 -n 2 --json-pp this.json /tmp/case-sensitive-paths-webpack-plugin/demo/package.json --verbose
 Setup plugin: output:json-pp...
 Setup plugin: output_filter:only-findings...
 Setup plugin: post_scan:package-root...
 Setup plugin: scan:info...
 Setup plugin: scan:copyrights...
 Setup plugin: scan:licenses...
 Setup plugin: scan:packages...
Collect file inventory...
Scan files for: info, licenses, copyrights, packages with 2 process(es)...
Scanned: /tmp/case-sensitive-paths-webpack-plugin/demo/package.json
Run post-scans...
 Run post-scan: package-root...
Apply output-filters...
 Apply output-filter: only-findings...
Save scan results...
 Save scan results as: json-pp...
Scanning done.
Some files failed to scan properly:
Path: package.json
  ERROR: for scanner: packages:
  ERROR: Unknown error:
  Traceback (most recent call last):
    File "/tmp/scancode-toolkit-2.9.2/src/scancode/interrupt.py", line 91, in interruptible
      return NO_ERROR, func(*(args or ()), **(kwargs or {}))
    File "/tmp/scancode-toolkit-2.9.2/src/scancode/api.py", line 208, in get_package_info
      manifest = recognize_package(location)
    File "/tmp/scancode-toolkit-2.9.2/src/packagedcode/recognize.py", line 77, in recognize_package
      return package_type.recognize(location)
    File "/tmp/scancode-toolkit-2.9.2/src/packagedcode/npm.py", line 75, in recognize
      return parse(location)
    File "/tmp/scancode-toolkit-2.9.2/src/packagedcode/npm.py", line 192, in parse
      return build_package(package_data, base_dir)
    File "/tmp/scancode-toolkit-2.9.2/src/packagedcode/npm.py", line 259, in build_package
      func(value, package)
    File "/tmp/scancode-toolkit-2.9.2/src/packagedcode/npm.py", line 542, in dist_mapper
      integrity = dist.get('integrity') or None
  AttributeError: 'unicode' object has no attribute 'get'
Summary:        info, copyrights, licenses, packages with 2 process(es)
Errors count:   1
Scan Speed:     0.55 files/sec. 918.42 Bytes/sec.
Initial counts: 1 resource(s): 1 file(s) and 0 directorie(s) 
Final counts:   1 resource(s): 1 file(s) and 0 directorie(s) for 1.65 KB
Timings:
  setup_scan:licenses: 1.68s
  setup: 1.68s
  scan: 1.83s
  post-scan:package-root: 0.16s
  post-scan: 0.16s
  total: 3.69s
```

and the error would also be seen in the JSON (irrespective of running with `--verbose` or not)

**Comment by dabutvin** [comment]
Check out this file
https://github.com/browserify/module-deps/blob/master/test/invalid_pkg/package.json

This whole scancode run is ending up in deadletter because of the way we are running scancode in the crawler. I think we should make a better effort to collect scancode output for the rest of the run

**Comment by fossygirl** [comment]
@dabutvin Also wondering if there's anything to be done here?

**Comment by pombredanne** [comment]
@fossygirl this has been fixed in ScanCode alright (for a while now). See https://github.com/nexB/scancode-toolkit/issues/983  and https://github.com/nexB/scancode-toolkit/issues/1078
All the fixes are in the 3.0.2 release

**Comment by dabutvin** [comment]
I kicked off these components with the latest, I can check back and see if they succeeded tomorrow

**Comment by dabutvin** [comment]
okay, we are good to go here!
