### ISSUE TITLE
EntitySpec.fromUrl - url.match is causing TypeError 

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#181]
at https://github.com/clearlydefined/crawler/blob/master/lib/entitySpec.js#L7

```
TypeError: url.match is not a function or its return value is not iterable
    at Function.fromUrl (/opt/service/lib/entitySpec.js:7:77)
    at SourceExtract.toSpec (/opt/service/lib/baseHandler.js:138:44)
    at SourceExtract.canHandle (/opt/service/providers/process/sourceExtract.js:20:23)
    at list.filter.element (/opt/service/providers/fetch/dispatcher.js:63:43)
```

we call `toSpec()` from BaseHandler

**Comment by dabutvin** [comment]
this is no longer happening
