### ISSUE TITLE
405 response unhandled from NPM

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#214]
`StatusCodeError: 405 - {"code":"MethodNotAllowedError","message":"GET is not allowed"}`

There's tons in the logs, one example is processing GET `typescript@npm%3A%40msfast%2Ftypescript-platform-resolution `

**Comment by jeffmendoza** [comment]
@geneh check if still happening

**Comment by geneh** [comment]
We are still getting a lot of those. Other component examples:
component@cd:/npm/npmjs/-/@types/ember__debug
component@cd:/npm/npmjs/-/@types/basic-auth
component@cd:/npm/npmjs/-/@types/webpack-bundle-analyzer

**Comment by nellshamrell** [comment]
I ran a harvest on my local setup with npm/npmjs/-/@types/ember__debug and I still receiving that error:

```
service_1                    | GET /definitions/npm/npmjs/-/@types/ember__debug?expand=prs&matchCasing=false 200 590.348 ms - 477
crawler_1                    | POST /requests 201 7.100 ms - 7
crawler_1                    | [I] Traversed component@cd:/npm/npmjs/-/@types/ember__debug  {"loopName":"1","cid":"18a","root":"self","outcome":"Traversed","time":6,"crawlerId":"4c35663a-9b58-4135-9c31-77bf94c9698b","buildNumber":"0"}
crawler_1                    | [I] Traversed package@cd:/npm/npmjs/-/@types/ember__debug  {"loopName":"1","cid":"18b","root":"component@cd:/npm/npmjs/-/@types/ember__debug","outcome":"Traversed","time":3,"crawlerId":"4c35663a-9b58-4135-9c31-77bf94c9698b","buildNumber":"0"}
crawler_1                    | trackException:
crawler_1                    | Error: StatusCodeError: 405 - {"code":"MethodNotAllowedError","message":"GET is not allowed"}
crawler_1                    |     at new StatusCodeError (/opt/service/node_modules/request-promise-core/lib/errors.js:32:15)
crawler_1                    |     at Request.plumbing.callback (/opt/service/node_modules/request-promise-core/lib/plumbing.js:104:33)
crawler_1                    |     at Request.RP$callback [as _callback] (/opt/service/node_modules/request-promise-core/lib/plumbing.js:46:31)
crawler_1                    |     at Request.self.callback (/opt/service/node_modules/request/request.js:185:22)
crawler_1                    |     at Request.emit (events.js:314:20)
crawler_1                    |     at Request.EventEmitter.emit (domain.js:483:12)
crawler_1                    |     at Request.<anonymous> (/opt/service/node_modules/request/request.js:1161:10)
crawler_1                    |     at Request.emit (events.js:314:20)
crawler_1                    |     at Request.EventEmitter.emit (domain.js:483:12)
```
