### ISSUE TITLE
null ref in rubyGemsFetch

### ISSUE THREAD

**Issue by dabutvin** [clearlydefined/crawler#236]
it looks protected, but we are getting several instances of this null reference

```
TypeError: Cannot read property 'version' of null
    at RubyGemsFetch.handle (/opt/service/providers/fetch/rubyGemsFetch.js:25:66)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

![image](https://user-images.githubusercontent.com/5168796/50796849-d1b9a400-1287-11e9-895b-163c67ae6486.png)

**Comment by dabutvin** [comment]
fixed in #237
