### ISSUE TITLE
protect temp file cleanup from errors

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#26]
```
{ Error: ENOENT: no such file or directory, lstat 'c:\temp\cd-I2LRbP\html.tmbundle\Templates\HTML – 4.0 Strict' at Object.fs.lstatSync (fs.js:941:11) at _rmdirRecursiveSync (c:\git\cd\crawler\node_modules\tmp\lib\tmp.js:300:19) at _cleanupCallback (c:\git\cd\crawler\node_modules\tmp\lib\tmp.js:446:7) at __dirname._completeRequest.request.getTrackedCleanups.forEach.cleanup (C:\git\ghcrawler\lib\crawler.js:276:74) at Array.forEach (<anonymous>) at Crawler._completeRequest (C:\git\ghcrawler\lib\crawler.js:276:55) at _fulfilled (C:\git\ghcrawler\node_modules\q\q.js:834:54) at Promise.then.Q.nextTick.self.promiseDispatch.done 
```

**Comment by jeffmcaffer** [comment]
Done changes to GHcrawler
