### ISSUE TITLE
invalid char in header error

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#28]
this seems to happen after the various git clone error or where something else goes wrong. unclear where or what's causing it

```
TypeError:
   at validateHeader (at validateHeader (_http_outgoing.js:497:11): _http_outgoing.js: 497)
   at ClientRequest.setHeader (at ClientRequest.setHeader (_http_outgoing.js:501:3): _http_outgoing.js: 501)
   at new ClientRequest (at new ClientRequest (_http_client.js:173:14): _http_client.js: 173)
   at Object.request (at Object.request (http.js:38:10): http.js: 38)
   at Object.request (at Object.request (https.js:239:15): https.js: 239)
   at Request.start (at Request.start (C:\git\ghcrawler\node_modules\request\request.js:740:32): C:\git\ghcrawler\node_modules\request\request.js: 740)
   at Request.write (at Request.write (C:\git\ghcrawler\node_modules\request\request.js:1380:10): C:\git\ghcrawler\node_modules\request\request.js: 1380)
   at end (at end (C:\git\ghcrawler\node_modules\request\request.js:552:18): C:\git\ghcrawler\node_modules\request\request.js: 552)
   at Immediate.<anonymous> (at Immediate.<anonymous> (C:\git\ghcrawler\node_modules\request\request.js:581:7): C:\git\ghcrawler\node_modules\request\request.js: 581)
   at runCallback (at runCallback (timers.js:789:20): timers.js: 789)
   at tryOnImmediate (at tryOnImmediate (timers.js:751:5): timers.js: 751)
   at processImmediate [as _immediateCallback] (at processImmediate [as _immediateCallback] (timers.js:722:5): timers.js: 722)

```

**Comment by jeffmcaffer** [comment]
need to dig into this if it happens again.
