### ISSUE TITLE
ambiguous argument checking out lodash

### ISSUE THREAD

**Issue by jeffmcaffer** [clearlydefined/crawler#29]
{ Error: Command failed: cd c:/temp/cd-NIh5E1 && git clone https://github.com/lodash/lodash.git && cd lodash && git reset --hard 3.0.1-npm-packages1 Cloning into 'lodash'... fatal: ambiguous argument '3.0.1-npm-packages1': unknown revision or path not in the working tree. Use '--' to separate paths from revisions, like this: 'git <command> [<revision>...] -- [<file>...]' at ChildProcess.exithandler (child_process.js:275:12) at emitTwo (events.js:126:13) at ChildProcess.emit (events.js:214:7) at maybeClose (internal/child_process.js:925:16) at

**Comment by jeffmcaffer** [comment]
my bug. the version number ended up with a '1' on the end.
