### ISSUE TITLE
Error 403 Forbidden when fetching Ruby gems

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#328]
```
2019-07-29T22:34:42.899496345Z trackException:
2019-07-29T22:34:42.906907175Z Error: Error: 403 Forbidden
2019-07-29T22:34:42.906947384Z     at Request.nodeRequest.get [as _callback] (/opt/service/providers/fetch/rubyGemsFetch.js:57:51)
2019-07-29T22:34:42.906955864Z     at Request.self.callback (/opt/service/node_modules/request/request.js:185:22)
2019-07-29T22:34:42.906962799Z     at Request.emit (events.js:198:13)
2019-07-29T22:34:42.90696951Z     at Request.<anonymous> (/opt/service/node_modules/request/request.js:1161:10)
2019-07-29T22:34:42.906977022Z     at Request.emit (events.js:203:15)
2019-07-29T22:34:42.906983127Z     at IncomingMessage.<anonymous> (/opt/service/node_modules/request/request.js:1083:12)
2019-07-29T22:34:42.906989691Z     at Object.onceWrapper (events.js:286:20)
2019-07-29T22:34:42.906995992Z     at IncomingMessage.emit (events.js:203:15)
2019-07-29T22:34:42.907002137Z     at endReadableNT (_stream_readable.js:1129:12)
2019-07-29T22:34:42.907007591Z     at process._tickCallback (internal/process/next_tick.js:63:19)
2019-07-29T22:34:42.907013208Z     at AzureApplicationInsightsLogger.log (/opt/service/node_modules/winston-azure-application-insights/lib/winston-azure-application-insights.js:159:12)
2019-07-29T22:34:42.907019389Z     at transportLog (/opt/service/node_modules/winston/lib/winston/logger.js:234:15)
2019-07-29T22:34:42.907025712Z     at /opt/service/node_modules/winston/node_modules/async/lib/async.js:157:13
2019-07-29T22:34:42.90703192Z     at _each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:57:9)
2019-07-29T22:34:42.907038412Z     at Object.async.each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:156:9)
2019-07-29T22:34:42.90704503Z     at exports.Logger.Logger.log (/opt/service/node_modules/winston/lib/winston/logger.js:246:9)
2019-07-29T22:34:42.907051345Z     at exports.Logger.log (/opt/service/node_modules/diagnostic-channel-publishers/dist/src/winston.pub.js:53:28)
2019-07-29T22:34:42.907058171Z     at exports.Logger.target.(anonymous function) [as error] (/opt/service/node_modules/winston/lib/winston/common.js:54:18)
2019-07-29T22:34:42.907065108Z     at Crawler._errorHandler (/opt/service/node_modules/ghcrawler/lib/crawler.js:127:19)
2019-07-29T22:34:42.907071723Z     at _rejected (/opt/service/node_modules/q/q.js:864:24)
2019-07-29T22:34:42.907078015Z     at /opt/service/node_modules/q/q.js:890:30
2019-07-29T22:34:42.907084Z     at Promise.when (/opt/service/node_modules/q/q.js:1142:31)
2019-07-29T22:34:42.907106454Z     at Promise.promise.promiseDispatch (/opt/service/node_modules/q/q.js:808:41)
2019-07-29T22:34:42.90711173Z     at /opt/service/node_modules/q/q.js:624:44
2019-07-29T22:34:42.907116882Z     at runSingle (/opt/service/node_modules/q/q.js:137:13)
2019-07-29T22:34:42.90712214Z     at flush (/opt/service/node_modules/q/q.js:125:13)
2019-07-29T22:34:43.294244707Z [I] Error gem@cd:/gem/rubygems/-/sidekiq-pro/0.0.1 403 Forbidden
2019-07-29T22:34:43.294307503Z 
2019-07-29T22:34:43.294314962Z Error: 403 Forbidden
2019-07-29T22:34:43.294320574Z     at Request.nodeRequest.get [as _callback] (/opt/service/providers/fetch/rubyGemsFetch.js:57:51)
2019-07-29T22:34:43.294325947Z     at Request.self.callback (/opt/service/node_modules/request/request.js:185:22)
2019-07-29T22:34:43.294330764Z     at Request.emit (events.js:198:13)
2019-07-29T22:34:43.294336934Z     at Request.<anonymous> (/opt/service/node_modules/request/request.js:1161:10)
2019-07-29T22:34:43.294343173Z     at Request.emit (events.js:203:15)
2019-07-29T22:34:43.294348578Z     at IncomingMessage.<anonymous> (/opt/service/node_modules/request/request.js:1083:12)
2019-07-29T22:34:43.294354771Z     at Object.onceWrapper (events.js:286:20)
2019-07-29T22:34:43.294359397Z     at IncomingMessage.emit (events.js:203:15)
2019-07-29T22:34:43.294364547Z     at endReadableNT (_stream_readable.js:1129:12)
2019-07-29T22:34:43.294369301Z     at process._tickCallback (internal/process/next_tick.js:63:19) {"loopName":"0","cid":"1s","root":"component@cd:/gem/rubygems/-/sidekiq-pro/0.0.1","outcome":"Error","time":674,"crawlerId":"crawler-5dddd97bcd-94m5s","crawlerHost":"Google","buildNumber":"20190722.1"}
```

**Comment by geneh** [comment]
There are still hundreds of thousands of similar errors daily causing Ruby gems not to be crawled at all. This functionality is now broken.
Another example:
```
Error gem@cd:/gem/rubygems/-/yaml-lint/0.0.6 403 Forbidden

Error: 403 Forbidden
    at Request._callback (/opt/service/providers/fetch/rubyGemsFetch.js:57:51)
    at Request.self.callback (/opt/service/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/opt/service/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:215:7)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/opt/service/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:299:28)
    at IncomingMessage.emit (events.js:215:7)
```
Affected request example: GET https://rubygems.org/downloads/yaml-lint-0.0.6.gem
```
<Error>
  <Code>AccessDenied</Code>
  <Message>Access Denied</Message>
  <RequestId>841F437AB0C83F40</RequestId>
  <HostId>
    TC6WB+i2al3AvaXqpWvxJmEgjaOrmAEadk+4VGDXztvylQ3U4f4Pxek/fHtMLw1lqefmvB6cPAo=
  </HostId>
</Error>
```
One of response headers:
`Upgrade-Insecure-Requests: 1`

**Comment by geneh** [comment]
Investigating further:
https://guides.rubygems.org/rubygems-org-api/#api-authorization
API Authorization

> Some API calls require an Authorization header. To find your API key, click on your username when logged in to RubyGems.org and then click on ‘Edit Profile’.

To protect the RubyGems.org service from abuse, both intentionally and unintentionally, we have rate limits in place for some of our endpoints. Some endpoints may be cached by our CDN at times and therefore may allow higher request rates. The following is a general guideline for the rate limit rules.

    API and website: 10 requests per second
    Dependency API: 15 requests per second
    Website sign up, sign in, api key, and forgot password: 100 requests per 10 minutes

Users who hit a rate limit will see HTTP 429 responses, for the remainder of the limit window. Usually this is just a few minutes.

The RubyGems.org team may occasionally blackhole user IP addresses for extreme cases to protect the platform. If you think this has happened to you, please submit a help ticket and we’ll be happy to look at it.

---
The following needs to be done:

- [ ] Check whether this API requires authentication.
- [ ] Implement "slow queue" - related to https://github.com/clearlydefined/crawler/issues/310
- [ ] Once the slow queue is implemented, open a help desk ticket to remove the blacklisted IPs.

**Comment by geneh** [comment]
This issue is now resolved by https://github.com/clearlydefined/crawler/pull/365.
