### ISSUE TITLE
Maven search - 429 Too Many Requests

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#355]
There are hundreds of thousands errors in the logs daily:
```
StatusCodeError: 429 - "<html>\r\n<head><title>429 Too Many Requests</title></head>\r\n<body>\r\n<center><h1>429 Too Many Requests</h1></center>\r\n<hr><center>nginx/1.16.1</center>\r\n</body>\r\n</html>\r\n"
    at new StatusCodeError (/opt/service/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/opt/service/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/opt/service/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/opt/service/node_modules/request/request.js:185:22)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:476:20)
    at Request.<anonymous> (/opt/service/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:210:5)
    at Request.EventEmitter.emit (domain.js:476:20)
    at IncomingMessage.<anonymous> (/opt/service/node_modules/request/request.js:1083:12) {
  name: 'StatusCodeError',
  statusCode: 429,
  message: '429 - "<html>\\r\\n<head><title>429 Too Many Requests</title></head>\\r\\n<body>\\r\\n<center><h1>429 Too Many Requests</h1></center>\\r\\n<hr><center>nginx/1.16.1</center>\\r\\n</body>\\r\\n</html>\\r\\n"',
  error: '<html>\r\n' +
    '<head><title>429 Too Many Requests</title></head>\r\n' +
    '<body>\r\n' +
    '<center><h1>429 Too Many Requests</h1></center>\r\n' +
    '<hr><center>nginx/1.16.1</center>\r\n' +
    '</body>\r\n' +
    '</html>\r\n',
  options: {
    url: 'https://search.maven.org/remotecontent?filepath=org/sonatype/oss/oss-parent/7/oss-parent-7.pom',
    json: false,
    callback: [Function: RP$callback],
    transform: undefined,
    simple: true,
    resolveWithFullResponse: false,
    transform2xxOnly: false
  },
...
```
Possible solutions:
1. Backoff and retry.
1. Slow queue. See https://github.com/clearlydefined/crawler/issues/328 & https://github.com/clearlydefined/crawler/issues/310.

**Comment by nellshamrell** [comment]
At this time I cannot reproduce this. If anyone sees this in the future, please feel free to re-open this and we will investigate further.
