### ISSUE TITLE
TypeError: Cannot read property 'project' of null at MavenFetch._getPom

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#366]
```
TypeError: Cannot read property 'project' of null
    at MavenFetch._getPom (/opt/service/providers/fetch/mavencentralFetch.js:111:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async MavenFetch._getPoms (/opt/service/providers/fetch/mavencentralFetch.js:93:17)
    at async MavenFetch.handle (/opt/service/providers/fetch/mavencentralFetch.js:38:18)
    at async FetchDispatcher._dispatchFetch (/opt/service/providers/fetch/dispatcher.js:57:5)
    at async Crawler._logStartEnd (/opt/service/ghcrawler/lib/crawler.js:527:26)
    at async Crawler._run (/opt/service/ghcrawler/lib/crawler.js:73:25)
```

**Comment by brphelps** [comment]
Issue does not seem to be happening anymore, looked at operational logs: 
exceptions | where outerMessage contains "Cannot read property 'project' of null"

And found nothing

**Comment by geneh** [comment]
Error maven@cd:/maven/mavencentral/org.pegdown/pegdown/1.0.0 Cannot read property 'project' of null

 

TypeError: Cannot read property 'project' of null
    at MavenFetch._getPom (/opt/service/providers/fetch/mavencentralFetch.js:111:16)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async MavenFetch._getPoms (/opt/service/providers/fetch/mavencentralFetch.js:93:17)
    at async MavenFetch.handle (/opt/service/providers/fetch/mavencentralFetch.js:38:18)
    at async FetchDispatcher._dispatchFetch (/opt/service/providers/fetch/dispatcher.js:57:5)
    at async Crawler._logStartEnd (/opt/service/ghcrawler/lib/crawler.js:527:26)
    at async Crawler._run (/opt/service/ghcrawler/lib/crawler.js:73:25)

**Comment by nellshamrell** [comment]
I was able to confirm this by running the ClearlyDefined services locally and navigating to http://localhost:3000/definitions/maven/mavencentral/org.pegdown/pegdown/1.0.0

```
crawler_1                    | [I] Traversed component@cd:/maven/mavencentral/org.pegdown/pegdown/1.0.0  {"loopName":"1","cid":"j7","root":"self","outcome":"Traversed","time":2,"crawlerId":"4c35663a-9b58-4135-9c31-77bf94c9698b","buildNumber":"0"}
crawler_1                    | [I] Traversed package@cd:/maven/mavencentral/org.pegdown/pegdown/1.0.0  {"loopName":"1","cid":"j8","root":"component@cd:/maven/mavencentral/org.pegdown/pegdown/1.0.0","outcome":"Traversed","time":1,"crawlerId":"4c35663a-9b58-4135-9c31-77bf94c9698b","buildNumber":"0"}
crawler_1                    | trackException:
crawler_1                    | Error: TypeError: Cannot read property 'project' of null
crawler_1                    |     at MavenFetch._getPom (/opt/service/providers/fetch/mavencentralFetch.js:111:16)
crawler_1                    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
crawler_1                    |     at async MavenFetch._getPoms (/opt/service/providers/fetch/mavencentralFetch.js:93:17)
crawler_1                    |     at async MavenFetch.handle (/opt/service/providers/fetch/mavencentralFetch.js:38:18)
crawler_1                    |     at async FetchDispatcher._dispatchFetch (/opt/service/providers/fetch/dispatcher.js:57:5)
crawler_1                    |     at async Crawler._logStartEnd (/opt/service/ghcrawler/lib/crawler.js:527:26)
crawler_1                    |     at async Crawler._run (/opt/service/ghcrawler/lib/crawler.js:73:25)
crawler_1                    |     at AzureApplicationInsightsLogger.log (/opt/service/node_modules/winston-azure-application-insights/lib/winston-azure-application-insights.js:159:12)
crawler_1                    |     at transportLog (/opt/service/node_modules/winston/lib/winston/logger.js:234:15)
crawler_1                    |     at /opt/service/node_modules/winston/node_modules/async/lib/async.js:157:13
crawler_1                    |     at _each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:57:9)
crawler_1                    |     at Object.async.each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:156:9)
crawler_1                    |     at exports.Logger.Logger.log (/opt/service/node_modules/winston/lib/winston/logger.js:246:9)
crawler_1                    |     at exports.Logger.log (/opt/service/node_modules/diagnostic-channel-publishers/dist/src/winston.pub.js:53:28)
crawler_1                    |     at exports.Logger.target.<computed> [as error] (/opt/service/node_modules/winston/lib/winston/common.js:54:18)
crawler_1                    |     at Crawler._errorHandler (/opt/service/ghcrawler/lib/crawler.js:132:19)
crawler_1                    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
crawler_1                    | [I] Error maven@cd:/maven/mavencentral/org.pegdown/pegdown/1.0.0 Cannot read property 'project' of null
crawler_1                    |
crawler_1                    | TypeError: Cannot read property 'project' of null
crawler_1                    |     at MavenFetch._getPom (/opt/service/providers/fetch/mavencentralFetch.js:111:16)
crawler_1                    |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
crawler_1                    |     at async MavenFetch._getPoms (/opt/service/providers/fetch/mavencentralFetch.js:93:17)
crawler_1                    |     at async MavenFetch.handle (/opt/service/providers/fetch/mavencentralFetch.js:38:18)
crawler_1                    |     at async FetchDispatcher._dispatchFetch (/opt/service/providers/fetch/dispatcher.js:57:5)
crawler_1                    |     at async Crawler._logStartEnd (/opt/service/ghcrawler/lib/crawler.js:527:26)
crawler_1                    |     at async Crawler._run (/opt/service/ghcrawler/lib/crawler.js:73:25) {"loopName":"1","cid":"j9","root":"component@cd:/maven/mavencentral/org.pegdown/pegdown/1.0.0","outcome":"Error","time":579,"crawlerId":"4c35663a-9b58-4135-9c31-77bf94c9698b","buildNumber":"0"}
```
