### ISSUE TITLE
TypeError: Cannot read property 'substring' of null (packagist)

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#368]
```
TypeError: Cannot read property 'substring' of null
    at PackagistFetch._getDirRoot (/opt/service/providers/fetch/packagistFetch.js:77:42)
    at PackagistFetch.handle (/opt/service/providers/fetch/packagistFetch.js:30:37)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async FetchDispatcher._dispatchFetch (/opt/service/providers/fetch/dispatcher.js:57:5)
    at async Crawler._logStartEnd (/opt/service/ghcrawler/lib/crawler.js:527:26)
    at async Crawler._run (/opt/service/ghcrawler/lib/crawler.js:73:25) 
```

**Comment by geneh** [comment]
This issue happens due to decompressed package naming assumptions. The second part of the directory name is taken from the manifest's dist.reference which may sometimes be null. The solution should be more generic and resilient.
