### ISSUE TITLE
Components stuck in "Not Harvested."

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/crawler#394]
Here are some examples of components that are 'stuck' in "Not Harvested" and we want to curate these. Thanks!

https://clearlydefined.io/definitions/git/github/alexdrone/Buffer/e63342c
https://clearlydefined.io/definitions/git/github/xiph/opus/defbc37
https://clearlydefined.io/definitions/npm/npmjs/juturu/electron-remote/1.1.3
https://clearlydefined.io/definitions/npm/npmjs/progress/kendo-data-query/1.5.4
https://clearlydefined.io/definitions/maven/mavencentral/com.microsoft.appcenter/appcenter-distribute/2.4.1
https://clearlydefined.io/definitions/maven/mavencentral/com.microsoft.appcenter/appcenter-auth/2.3.0
https://clearlydefined.io/definitions/pypi/pypi/-/backports.ssl-match-hostname/3.7.0.1

**Comment by ariel11** [comment]
One issue is when component name has a _ - e.g. https://clearlydefined.io/definitions/pypi/pypi/-/websocket-client/0.57.0, https://pypi.org/project/websocket_client/

Fine if its a -.  Eg. https://pypi.org/project/msal-extensions/0.1.3/ and https://clearlydefined.io/definitions/pypi/pypi/-/msal-extensions/0.1.3

**Comment by nellshamrell** [comment]
I tried this locally with git/github/alexdrone/Buffer/e63342c and it appears to have the same issue.

I can confirm it queues up for harvest, and the logs show the various tools being run, but it's not updating as harvested:

```bash
service_1                    | GET /curations/git/github/alexdrone/buffer/e63342c?expand=prs 404 3.397 ms - 9
service_1                    | GET /harvest/git/github/alexdrone/buffer/e63342c?form=raw 304 11.484 ms - -
service_1                    | GET /suggestions/git/github/alexdrone/buffer/e63342c 404 5.904 ms - 9
service_1                    | [I] definition not available{"coordinates":"git/github/alexdrone/buffer/e63342c"}
service_1                    | GET /definitions/git/github/alexdrone/buffer/e63342c?expand=prs&matchCasing=false 200 570.463 ms - 673
crawler_1                    | POST /requests 201 0.841 ms - 7
crawler_1                    | [I] Traversed component@cd:/git/github/alexdrone/buffer/e63342c  {"loopName":"0","cid":"1po","root":"self","outcome":"Traversed","time":2,"crawlerId":"da62d530-3d93-4de8-936b-098a9b84bf2e","buildNumber":"0"}
crawler_1                    | [I] Traversed source@cd:/git/github/alexdrone/buffer/e63342c  {"loopName":"0","cid":"1pp","root":"component@cd:/git/github/alexdrone/buffer/e63342c","outcome":"Traversed","time":3,"crawlerId":"da62d530-3d93-4de8-936b-098a9b84bf2e","buildNumber":"0"}
crawler_1                    | [I] Processed clearlydefined@cd:/git/github/alexdrone/buffer/e63342c0ae6bf34bf21b2b9331f2ca76844c8983  {"loopName":"0","cid":"1pq","root":"component@cd:/git/github/alexdrone/buffer/e63342c","gitSize":11042,"k":11334,"count":51,"write":1,"outcome":"Processed","time":2151,"crawlerId":"da62d530-3d93-4de8-936b-098a9b84bf2e","buildNumber":"0"}
crawler_1                    | [I] Processed licensee@cd:/git/github/alexdrone/buffer/e63342c0ae6bf34bf21b2b9331f2ca76844c8983  {"loopName":"0","cid":"1pr","root":"component@cd:/git/github/alexdrone/buffer/e63342c","gitSize":11042,"write":1,"outcome":"Processed","time":2682,"crawlerId":"da62d530-3d93-4de8-936b-098a9b84bf2e","buildNumber":"0"}
crawler_1                    | [I] Analyzing scancode@cd:/git/github/alexdrone/buffer/e63342c0ae6bf34bf21b2b9331f2ca76844c8983 using ScanCode. input: /tmp/cd-Hmk1h1/buffer output: /tmp/cd-IJWayS {"crawlerId":"da62d530-3d93-4de8-936b-098a9b84bf2e","buildNumber":"0"}
crawler_1                    | [I] Processed scancode@cd:/git/github/alexdrone/buffer/e63342c0ae6bf34bf21b2b9331f2ca76844c8983  {"loopName":"0","cid":"1ps","root":"component@cd:/git/github/alexdrone/buffer/e63342c","gitSize":11042,"write":4,"outcome":"Processed","time":48167,"crawlerId":"da62d530-3d93-4de8-936b-098a9b84bf2e","buildNumber":"0"}
```

**Comment by nellshamrell** [comment]
I confirmed the same behavior for git/github/xiph/opus/defbc37

Interestingly, I received an error in the logs for npm/npmjs/juturu/electron-remote/1.1.3

```
crawler_1                    | [I] Traversed package@cd:/npm/npmjs/juturu/electron-remote/1.1.3  {"loopName":"1","cid":"2l","root":"component@cd:/npm/npmjs/juturu/electron-remote/1.1.3","outcome":"Traversed","time":1,"crawlerId":"4c35663a-9b58-4135-9c31-77bf94c9698b","buildNumber":"0"}
crawler_1                    | trackException:
crawler_1                    | Error: StatusCodeError: 405 - {"code":"MethodNotAllowedError","message":"GET is not allowed"}
crawler_1                    |     at new StatusCodeError (/opt/service/node_modules/request-promise-core/lib/errors.js:32:15)
crawler_1                    |     at Request.plumbing.callback (/opt/service/node_modules/request-promise-core/lib/plumbing.js:104:33)
crawler_1                    |     at Request.RP$callback [as _callback] (/opt/service/node_modules/request-promise-core/lib/plumbing.js:46:31)
crawler_1                    |     at Request.self.callback (/opt/service/node_modules/request/request.js:185:22)
crawler_1                    |     at Request.emit (events.js:314:20)
crawler_1                    |     at Request.EventEmitter.emit (domain.js:483:12)
crawler_1                    |     at Request.<anonymous> (/opt/service/node_modules/request/request.js:1161:10)
crawler_1                    |     at Request.emit (events.js:314:20)
crawler_1                    |     at Request.EventEmitter.emit (domain.js:483:12)
crawler_1                    |     at IncomingMessage.<anonymous> (/opt/service/node_modules/request/request.js:1083:12) {
crawler_1                    |   statusCode: 405,
crawler_1                    |   error: { code: 'MethodNotAllowedError', message: 'GET is not allowed' },
```

I'm not sure why this is happening, but this is definitely reproducible.
