### ISSUE TITLE
Error crashing crawler

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#80]
The following error crashes the crawler container. It doesn't happen too frequently. I am not sure what causes this error exactly yet.
```
2018-03-07T19:38:18.347907572Z /opt/service/node_modules/applicationinsights/AutoCollection/Exceptions.js:27
2018-03-07T19:38:18.347941773Z                         throw error;
2018-03-07T19:38:18.347955274Z                         ^
2018-03-07T19:38:18.347968074Z
2018-03-07T19:38:18.347980475Z Error: absolute path: /
2018-03-07T19:38:18.347992675Z     at /opt/service/node_modules/extract-zip/node_modules/yauzl/index.js:353:111
2018-03-07T19:38:18.348008876Z     at /opt/service/node_modules/extract-zip/node_modules/yauzl/index.js:473:5
2018-03-07T19:38:18.348021177Z     at /opt/service/node_modules/fd-slicer/index.js:32:7
2018-03-07T19:38:18.348033577Z     at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
2018-03-07T19:38:18.544291073Z npm ERR! code ELIFECYCLE
2018-03-07T19:38:18.550510423Z npm ERR! errno 7
2018-03-07T19:38:18.572934125Z npm ERR! clearlydefined-crawler@0.1.0 start: `node ./run.js`
2018-03-07T19:38:18.573279139Z npm ERR! Exit status 7
2018-03-07T19:38:18.573859562Z npm ERR!
2018-03-07T19:38:18.574219477Z npm ERR! Failed at the clearlydefined-crawler@0.1.0 start script.
2018-03-07T19:38:18.574471787Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-03-07T19:38:18.661030569Z
2018-03-07T19:38:18.661288880Z npm ERR! A complete log of this run can be found in:
2018-03-07T19:38:18.661571991Z npm ERR!     /root/.npm/_logs/2018-03-07T19_38_18_594Z-debug.log
 
2018-03-07 19:38:19.554 ERROR - Container for cdcrawler-dev_0 site cdcrawler-dev is unhealthy. Stopping site.
```

**Comment by geneh** [comment]
This error does not appear anymore. The following error is caused in gitCloner.js for a repo that does not exist. The code has to be wrapped in try-catch and the failing request should go to deadletter queue.
```
2018-03-12 22:35:02.346 INFO  - Container logs
2018-03-12T22:34:58.601230575Z trackException:
2018-03-12T22:34:58.604087197Z Error: { Error: Command failed: cd /tmp/cd-wd5In6 && git clone https://github.com/coin-or/bonmin.git --quiet && cd bonmin && git reset --hard 1.8.0 --quiet && git count-objects -v
2018-03-12T22:34:58.604112298Z fatal: ambiguous argument '1.8.0': unknown revision or path not in the working tree.
2018-03-12T22:34:58.604125099Z Use '--' to separate paths from revisions, like this:
2018-03-12T22:34:58.604137199Z 'git <command> [<revision>...] -- [<file>...]'
2018-03-12T22:34:58.604149500Z 
2018-03-12T22:34:58.604161000Z     at ChildProcess.exithandler (child_process.js:275:12)
2018-03-12T22:34:58.604172601Z     at emitTwo (events.js:126:13)
2018-03-12T22:34:58.604183901Z     at ChildProcess.emit (events.js:214:7)
2018-03-12T22:34:58.604195302Z     at maybeClose (internal/child_process.js:925:16)
2018-03-12T22:34:58.604206702Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2018-03-12T22:34:58.604218303Z   killed: false,
2018-03-12T22:34:58.604229503Z   code: 128,
2018-03-12T22:34:58.604240704Z   signal: null,
2018-03-12T22:34:58.604252004Z   cmd: 'cd /tmp/cd-wd5In6 && git clone https://github.com/coin-or/bonmin.git --quiet && cd bonmin && git reset --hard 1.8.0 --quiet && git count-objects -v' }
2018-03-12T22:34:58.604264605Z     at AzureApplicationInsightsLogger.log (/opt/service/node_modules/winston-azure-application-insights/lib/winston-azure-application-insights.js:122:12)
2018-03-12T22:34:58.604276605Z     at transportLog (/opt/service/node_modules/winston/lib/winston/logger.js:228:15)
2018-03-12T22:34:58.604300606Z     at /opt/service/node_modules/winston/node_modules/async/lib/async.js:157:13
2018-03-12T22:34:58.604313207Z     at _each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:57:9)
2018-03-12T22:34:58.604324807Z     at Object.async.each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:156:9)
2018-03-12T22:34:58.604336508Z     at exports.Logger.Logger.log (/opt/service/node_modules/winston/lib/winston/logger.js:240:9)
2018-03-12T22:34:58.604348008Z     at exports.Logger.target.(anonymous function) [as error] (/opt/service/node_modules/winston/lib/winston/common.js:54:18)
2018-03-12T22:34:58.604359909Z     at Crawler._errorHandler (/opt/service/node_modules/ghcrawler/lib/crawler.js:127:19)
2018-03-12T22:34:58.604371510Z     at _rejected (/opt/service/node_modules/q/q.js:844:24)
2018-03-12T22:34:58.604383010Z     at /opt/service/node_modules/q/q.js:870:30
2018-03-12T22:34:58.604394310Z     at Promise.when (/opt/service/node_modules/q/q.js:1122:31)
2018-03-12T22:34:58.604405911Z     at Promise.promise.promiseDispatch (/opt/service/node_modules/q/q.js:788:41)
2018-03-12T22:34:58.604417211Z     at /opt/service/node_modules/q/q.js:604:44
2018-03-12T22:34:58.604428412Z     at runSingle (/opt/service/node_modules/q/q.js:137:13)
2018-03-12T22:34:58.604440712Z     at flush (/opt/service/node_modules/q/q.js:125:13)
2018-03-12T22:34:58.604452113Z     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-03-12T22:34:58.836500654Z [I] Error clearlydefined@cd:/git/github/coin-or/bonmin/1.8.0 Command failed: cd /tmp/cd-wd5In6 && git clone https://github.com/coin-or/bonmin.git --quiet && cd bonmin && git reset --hard 1.8.0 --quiet && git count-objects -v
2018-03-12T22:34:58.836545756Z fatal: ambiguous argument '1.8.0': unknown revision or path not in the working tree.
2018-03-12T22:34:58.836558957Z Use '--' to separate paths from revisions, like this:
2018-03-12T22:34:58.836571057Z 'git <command> [<revision>...] -- [<file>...]'
2018-03-12T22:34:58.836583558Z {"loopName":"0","cid":"p4","root":"source@cd:/git/github/coin-or/Bonmin/1.8.0","outcome":"Error","time":4153}
```

**Comment by geneh** [comment]
Another occurrence:
```
2018-03-13 00:05:25.570 INFO  - Container logs
2018-03-13T00:05:24.001524160Z [I] Drained   _blank@null Waiting 5000 milliseconds{"loopName":"1","cid":"cp","root":"self","outcome":"Drained","time":1}

2018-03-13 00:05:50.580 INFO  - Container logs
2018-03-13T00:05:46.130289786Z [I] Analyzing scancode@cd:/git/github/krakenjs/post-robot/v7.0.15 using ScanCode. input: /tmp/cd-DJwrUU/post-robot output: /tmp/cd-wCgdXj

2018-03-13 00:05:55.714 INFO  - Container logs
2018-03-13T00:05:55.039431594Z /opt/service/node_modules/applicationinsights/AutoCollection/Exceptions.js:27
2018-03-13T00:05:55.039479995Z                         throw error;
2018-03-13T00:05:55.039494896Z                         ^
2018-03-13T00:05:55.039508596Z 
2018-03-13T00:05:55.039521797Z Error: absolute path: /
2018-03-13T00:05:55.039535097Z     at /opt/service/node_modules/extract-zip/node_modules/yauzl/index.js:353:111
2018-03-13T00:05:55.039548598Z     at /opt/service/node_modules/extract-zip/node_modules/yauzl/index.js:473:5
2018-03-13T00:05:55.039575399Z     at /opt/service/node_modules/fd-slicer/index.js:32:7
2018-03-13T00:05:55.039589999Z     at FSReqWrap.wrapper [as oncomplete] (fs.js:658:17)
2018-03-13T00:05:55.070082611Z npm ERR! code ELIFECYCLE
2018-03-13T00:05:55.070869439Z npm ERR! errno 7
2018-03-13T00:05:55.072781709Z npm ERR! clearlydefined-crawler@0.1.0 start: `node ./run.js`
2018-03-13T00:05:55.077202770Z npm ERR! Exit status 7
2018-03-13T00:05:55.077752990Z npm ERR! 
2018-03-13T00:05:55.078556720Z npm ERR! Failed at the clearlydefined-crawler@0.1.0 start script.
2018-03-13T00:05:55.078905132Z npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-03-13T00:05:55.090594258Z 
2018-03-13T00:05:55.091120278Z npm ERR! A complete log of this run can be found in:
2018-03-13T00:05:55.091444189Z npm ERR!     /root/.npm/_logs/2018-03-13T00_05_55_080Z-debug.log

2018-03-13 00:05:55.728 ERROR - Container for cdcrawler-prod_0 site cdcrawler-prod is unhealthy. Stopping site.
2018-03-13 00:06:17.372 INFO  - Starting container for site
2018-03-13 00:06:17.373 INFO  - docker run -d -p 47006:4000 --name cdcrawler-prod_0 -e DOCKER_CUSTOM_IMAGE_NAME=clearlydefinedprod.azurecr.io/clearlydefined/crawler:latest -e WEBSITE_SITE_NAME=cdcrawler-prod -e WEBSITE_AUTH_ENABLED=False -e PORT=4000 -e WEBSITE_ROLE_INSTANCE_ID=0 -e WEBSITE_INSTANCE_ID=e208e60551e725c66a76b094c76287058b3027588b79b12a76760f6d31a84e1f -e HTTP_LOGGING_ENABLED=1 clearlydefinedprod.azurecr.io/clearlydefined/crawler:latest  

2018-03-13 00:06:24.366 INFO  - Container cdcrawler-prod_0 for site cdcrawler-prod initialized successfully.
2018-03-13 00:06:29.375 INFO  - Container logs
2018-03-13T00:06:19.088948505Z 
2018-03-13T00:06:19.089027808Z > clearlydefined-crawler@0.1.0 start /opt/service
2018-03-13T00:06:19.089043109Z > node ./run.js
2018-03-13T00:06:19.089055109Z 
2018-03-13T00:06:22.414096593Z [I] appInitStart
```

**Comment by geneh** [comment]
Closing for now, will re-open if it occurs again.

**Comment by geneh** [comment]
This is caused by bad archives: https://stackoverflow.com/questions/21322416/unzip-warning-and-mapname

**Comment by geneh** [comment]
Resolved by https://github.com/clearlydefined/crawler/commit/981a00d18754a24e9b6568c41a374dfbe4d35fd5
From now on bad archives are going to end up in deadletters.
Related issue: https://github.com/maxogden/extract-zip/issues/65
