### ISSUE TITLE
Crawler should be able to handle versions containing forward slash

### ISSUE THREAD

**Issue by geneh** [clearlydefined/crawler#85]
The following components fail:
```
  { "type": "source", "url": "cd:/git/github/coin-or/Bonmin/releases/1.8.0" },
  { "type": "source", "url": "cd:/git/github/coin-or/Cbc/releases/2.9.0" },
```
Error:
```
2018-03-13T16:35:35.618750568Z trackException:
2018-03-13T16:35:35.619006079Z Error: { Error: Command failed: cd /tmp/cd-4K7OOS && git clone https://github.com/coin-or/cbc.git --quiet && cd cbc && git reset --hard releases --quiet && git count-objects -v
2018-03-13T16:35:35.619026080Z fatal: ambiguous argument 'releases': unknown revision or path not in the working tree.
2018-03-13T16:35:35.619039080Z Use '--' to separate paths from revisions, like this:
2018-03-13T16:35:35.619051281Z 'git <command> [<revision>...] -- [<file>...]'
2018-03-13T16:35:35.619063781Z 
2018-03-13T16:35:35.619075282Z     at ChildProcess.exithandler (child_process.js:275:12)
2018-03-13T16:35:35.619087182Z     at emitTwo (events.js:126:13)
2018-03-13T16:35:35.619098783Z     at ChildProcess.emit (events.js:214:7)
2018-03-13T16:35:35.619110583Z     at maybeClose (internal/child_process.js:925:16)
2018-03-13T16:35:35.619122284Z     at Socket.stream.socket.on (internal/child_process.js:346:11)
2018-03-13T16:35:35.619133984Z     at emitOne (events.js:116:13)
2018-03-13T16:35:35.619145385Z     at Socket.emit (events.js:211:7)
2018-03-13T16:35:35.619157085Z     at Pipe._handle.close [as _onclose] (net.js:567:12)
2018-03-13T16:35:35.619168886Z   killed: false,
2018-03-13T16:35:35.619180386Z   code: 128,
2018-03-13T16:35:35.619201087Z   signal: null,
2018-03-13T16:35:35.619213588Z   cmd: 'cd /tmp/cd-4K7OOS && git clone https://github.com/coin-or/cbc.git --quiet && cd cbc && git reset --hard releases --quiet && git count-objects -v' }
2018-03-13T16:35:35.619226688Z     at AzureApplicationInsightsLogger.log (/opt/service/node_modules/winston-azure-application-insights/lib/winston-azure-application-insights.js:122:12)
2018-03-13T16:35:35.619238989Z     at transportLog (/opt/service/node_modules/winston/lib/winston/logger.js:228:15)
2018-03-13T16:35:35.619250889Z     at /opt/service/node_modules/winston/node_modules/async/lib/async.js:157:13
2018-03-13T16:35:35.619262690Z     at _each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:57:9)
2018-03-13T16:35:35.619274390Z     at Object.async.each (/opt/service/node_modules/winston/node_modules/async/lib/async.js:156:9)
2018-03-13T16:35:35.619286291Z     at exports.Logger.Logger.log (/opt/service/node_modules/winston/lib/winston/logger.js:240:9)
2018-03-13T16:35:35.619298091Z     at exports.Logger.target.(anonymous function) [as error] (/opt/service/node_modules/winston/lib/winston/common.js:54:18)
2018-03-13T16:35:35.619310192Z     at Crawler._errorHandler (/opt/service/node_modules/ghcrawler/lib/crawler.js:127:19)
2018-03-13T16:35:35.619321992Z     at _rejected (/opt/service/node_modules/q/q.js:844:24)
2018-03-13T16:35:35.619333693Z     at /opt/service/node_modules/q/q.js:870:30
2018-03-13T16:35:35.619345193Z     at Promise.when (/opt/service/node_modules/q/q.js:1122:31)
2018-03-13T16:35:35.619356794Z     at Promise.promise.promiseDispatch (/opt/service/node_modules/q/q.js:788:41)
2018-03-13T16:35:35.619369594Z     at /opt/service/node_modules/q/q.js:604:44
2018-03-13T16:35:35.619381195Z     at runSingle (/opt/service/node_modules/q/q.js:137:13)
2018-03-13T16:35:35.619392795Z     at flush (/opt/service/node_modules/q/q.js:125:13)
2018-03-13T16:35:35.619404396Z     at _combinedTickCallback (internal/process/next_tick.js:131:7)
2018-03-13T16:35:35.892072951Z [I] Error clearlydefined@cd:/git/github/coin-or/cbc/releases Command failed: cd /tmp/cd-4K7OOS && git clone https://github.com/coin-or/cbc.git --quiet && cd cbc && git reset --hard releases --quiet && git count-objects -v
2018-03-13T16:35:35.892118853Z fatal: ambiguous argument 'releases': unknown revision or path not in the working tree.
2018-03-13T16:35:35.892132154Z Use '--' to separate paths from revisions, like this:
2018-03-13T16:35:35.892144054Z 'git <command> [<revision>...] -- [<file>...]'
2018-03-13T16:35:35.892156255Z {"loopName":"1","cid":"gk2","root":"source@cd:/git/github/coin-or/Cbc/releases/2.9.0","outcome":"Error","time":11721}
```

**Comment by geneh** [comment]
Slashes in component version names are not going to be supported for now since they are not following semver.
